package tds.testpackage.model;

import org.junit.Test;

import java.util.Arrays;
import java.util.HashSet;
import java.util.List;
import java.util.stream.Collectors;

import tds.testpackage.model.SegmentForm;

import static org.assertj.core.api.Java6Assertions.assertThat;

public class FormIdTest {
    public static List<String> formIds = Arrays.asList(
    "PracTest::ELAG5::FA17::BRL",
    "PracTest::ELAG6::FA17::ENU",
    "PracTest::ELAG6::FA17::BRL",
    "PracTest::ELAG7::FA17::ENU",
    "PracTest::ELAG7::FA17::BRL",
    "PracTest::ELAG8::FA17::ENU",
    "PracTest::ELAG8::FA17::BRL",
    "PracTest::ELAG11::FA17::ENU",
    "PracTest::ELAG11::FA17::BRL",
    "PracTest::ELAG3::Perf::S1::FA17::ENU",
    "PracTest::ELAG3::Perf::S1::FA17::BRL",
    "PracTest::ELAG3::Perf::S2::FA17::ENU",
    "PracTest::ELAG3::Perf::S2::FA17::BRL",
    "PracTest::ELAG4::Perf::S1::FA17::ENU",
    "PracTest::ELAG4::Perf::S1::FA17::BRL",
    "PracTest::ELAG4::Perf::S2::FA17::ENU",
    "PracTest::ELAG4::Perf::S2::FA17::BRL",
    "PracTest::ELAG5::Perf::S1::FA17::ENU",
    "PracTest::ELAG5::Perf::S1::FA17::BRL",
    "PracTest::ELAG5::Perf::S2::FA17::ENU",
    "PracTest::ELAG5::Perf::S2::FA17::BRL",
    "PracTest::ELAG6::Perf::S1::FA17::ENU",
    "PracTest::ELAG6::Perf::S1::FA17::BRL",
    "PracTest::ELAG6::Perf::S2::FA17::ENU",
    "PracTest::ELAG6::Perf::S2::FA17::BRL",
    "PracTest::ELAG7::Perf::S1::FA17::ENU",
    "PracTest::ELAG7::Perf::S1::FA17::BRL",
    "PracTest::ELAG7::Perf::S2::FA17::ENU",
    "PracTest::ELAG7::Perf::S2::FA17::BRL",
    "PracTest::ELAG8::Perf::S1::FA17::ENU",
    "PracTest::ELAG8::Perf::S1::FA17::BRL",
    "PracTest::ELAG8::Perf::S2::FA17::ENU",
    "PracTest::ELAG8::Perf::S2::FA17::BRL",
    "PracTest::ELAG11::Perf::S1::FA17::ENU",
    "PracTest::ELAG11::Perf::S1::FA17::BRL",
    "PracTest::ELAG11::Perf::S2::FA17::ENU",
    "PracTest::ELAG11::Perf::S2::FA17::BRL",
    "Math Training 3-5::FA 17",
    "Math Training 3-5::FA 17::Braille",
    "Math Training 3-5::FA 17::Spanish",
    "ELA Training 3-5::FA 17",
    "ELA Training 3-5::FA 17::Braille",
    "Math Training 6::FA 17",
    "Math Training 6::FA 17::Braille",
    "Math Training 6::FA 17::Spanish",
    "Math Training 6-8::FA 17",
    "Math Training 6-8::FA 17::Braille",
    "Math Training 6-8::FA 17::Spanish",
    "ELA Training 6-8::FA 17",
    "ELA Training 6-8::FA 17::Braille",
    "Math Training HS::FA 17",
    "Math Training HS::FA 17::Braille",
    "Math Training HS::FA 17::Spanish",
    "ELA Training HS::FA 17",
    "ELA Training HS::FA 17::Braille",
    "Training SH FA17",
    "Student Help::IRP",
    "IRP::ELAG3::Perf::S1::SP15",
    "IRP::ELAG3::Perf::S2::SP15",
    "IRP::ELAG7::Perf::S1::SP15",
    "IRP::ELAG7::Perf::S2::SP15",
    "IRP::ELAG11::Perf::S1::SP15",
    "IRP::ELAG11::Perf::S2::SP15",
    "IRP::MathG3::Perf::SP15",
    "IRP::MathG7::Perf::SP15",
    "IRP::MathG11::Perf::SP15",
    "PracTest::ELAG11::FA16",
    "PracTest::ELAG11::FA16::BRL",
    "PracTest::MG7::S1::SP14",
    "IRP::MathG3::Perf::SP15::COMBINED",
    "IRP::ELAG11::Perf::S1::SP15::COMBINED",
    "IRP::ELAG11::Perf::S2::SP15::COMBINED",
    "IRP::MathG11::Perf::SP15::COMBINED",
    "IRP::MathG7::Perf::SP15::COMBINED",
    "PracTest::ELAG4::Perf::S1::SP14",
    "PracTest::ELAG4::Perf::S1::SP14::Braille",
    "PracTest::ELAG4::Perf::S2::SP14",
    "PracTest::ELAG4::Perf::S2::SP14::Braille",
    "PracTest::ELAG8::SP14",
    "PracTest::ELAG8::SP14::Braille",
    "PracTest::ELAG7::SP14",
    "PracTest::ELAG7::SP14::Braille",
    "PracTest::ELAG8::Perf::S1::SP14",
    "PracTest::ELAG8::Perf::S1::SP14::Braille",
    "PracTest::ELAG8::Perf::S2::SP14",
    "PracTest::ELAG8::Perf::S2::SP14::Braille",
    "IRP::ELAG3::B1::SP16",
    "TTB:IRP::ELAG3::B1::SP16",
    "IRP::ELAG3::B2::SP16",
    "TTB::IRP::ELAG3::B2::SP16",
    "PracTest::MG4::S1::SP14",
    "PracTest::MG4::S1::SP14::Braille",
    "PracTest::MG4::S1::SP14::ESN",
    "IRP::ELAG7::B2::SP16",
    "TTB::IRP::ELAG7::B2::SP16",
    "IRP::ELAG7::B1::SP16",
    "TTB::IRP::ELAG7::B1::SP16",
    "PracTest::MG3::FA17::ENU",
    "PracTest::MG3::FA17::BRL",
    "PracTest::MG3::FA17::SPA",
    "PracTest::MG4::FA17::ENU",
    "PracTest::MG4::FA17::BRL",
    "PracTest::MG4::FA17::SPA",
    "PracTest::MG5::FA17::ENU",
    "PracTest::MG5::FA17::BRL",
    "PracTest::MG5::FA17::SPA",
    "PracTest::MG6::S1::FA17::ENU",
    "PracTest::MG6::S1::FA17::BRL",
    "PracTest::MG6::S1::FA17::SPA",
    "PracTest::MG6::S2::FA17::ENU",
    "PracTest::MG6::S2::FA17::BRL",
    "PracTest::MG6::S2::FA17::SPA",
    "PracTest::MG7::S1::FA17::ENU",
    "PracTest::MG7::S1::FA17::BRL",
    "PracTest::MG7::S1::FA17::SPA",
    "PracTest::MG7::S2::FA17::ENU",
    "PracTest::MG7::S2::FA17::BRL",
    "PracTest::MG7::S2::FA17::SPA",
    "PracTest::MG8::S1::FA17::ENU",
    "PracTest::MG8::S1::FA17::BRL",
    "PracTest::MG8::S1::FA17::SPA",
    "PracTest::MG8::S2::FA17::ENU",
    "PracTest::MG8::S2::FA17::BRL",
    "PracTest::MG8::S2::FA17::SPA",
    "PracTest::MG11::S1::FA17::ENU",
    "PracTest::MG11::S1::FA17::BRL",
    "PracTest::MG11::S1::FA17::SPA",
    "PracTest::MG11::S2::FA17::ENU",
    "PracTest::MG11::S2::FA17::BRL",
    "PracTest::MG11::S2::FA17::SPA",
    "PracTest::MG3::Perf::FA17::ENU",
    "PracTest::MG3::Perf::FA17::BRL",
    "PracTest::MG3::Perf::FA17::SPA",
    "PracTest::MG4::Perf::FA17::ENU",
    "PracTest::MG4::Perf::FA17::BRL",
    "PracTest::MG4::Perf::FA17::SPA",
    "PracTest::MG5::Perf::FA17::ENU",
    "PracTest::MG5::Perf::FA17::BRL",
    "PracTest::MG5::Perf::FA17::SPA",
    "PracTest::MG6::Perf::FA17::ENU",
    "PracTest::MG6::Perf::FA17::BRL",
    "PracTest::MG6::Perf::FA17::SPA",
    "PracTest::MG7::Perf::FA17::ENU",
    "PracTest::MG7::Perf::FA17::BRL",
    "PracTest::MG7::Perf::FA17::SPA",
    "PracTest::MG8::Perf::FA17::ENU",
    "PracTest::MG8::Perf::FA17::BRL",
    "PracTest::MG8::Perf::FA17::SPA",
    "PracTest::MG11::Perf::FA17::ENU",
    "PracTest::MG11::Perf::FA17::BRL",
    "PracTest::MG11::Perf::FA17::SPA",
    "PracTest::ELAG3::FA17::ENU",
    "PracTest::ELAG3::FA17::BRL",
    "PracTest::ELAG4::FA17::ENU",
    "PracTest::ELAG4::FA17::BRL",
    "PracTest::ELAG5::FA17::ENU",
    "IAB-G4E-BriefWrites-2018 ENG",
    "IAB-G4E-BriefWrites-2018 BRL",
    "IAB-G7E-ListenInterpret-2018 ENG",
    "IAB-G7E-ListenInterpret-2018 BRL",
    "IAB-G3M-OA-2018 ENG",
    "IAB-G3M-OA-2018 BRL",
    "IAB-G3M-OA-2018 SPA",
    "IAB-G4M-PT-2018 ENG",
    "IAB-G4M-PT-2018 BRL",
    "IAB-G4M-PT-2018 SPA",
    "Student Help IAB Math 2018",
    "IAB-G5E-ListenInterpret-2018 ENG",
    "IAB-G5E-ListenInterpret-2018 BRL",
    "IAB-G4M-MD-2018 ENG",
    "IAB-G4M-MD-2018 BRL",
    "IAB-G4M-MD-2018 SPA",
    "IAB-G5M-OA-2018 ENG",
    "IAB-G5M-OA-2018 BRL",
    "IAB-G5M-OA-2018 SPA",
    "IAB-G11E-PT1-2018 ENG",
    "IAB-G11E-PT2-2018 ENG",
    "IAB-G5E-BriefWrites-2018 ENG",
    "ELA ICA Perf G6a 2018 ENG",
    "ELA ICA Perf G6b 2018 ENG",
    "ELA ICA G6 2018 ENG");

    @Test
    public void generateFormKeys() {
        // validate the uniqueness of hash generation method for form ids
        List<Integer> formKeys = formIds.stream().map(SegmentForm::generateFormKey).collect(Collectors.toList());

        assertThat(formKeys.size()).isEqualTo(new HashSet<>(formKeys).size());
    }
}
