# this app is expected to run inside the security perimeter so disable security for actuator end-points and,
# since those are the only end-points, switch to a less standard port using the main server.port config
management:
  port: 8008
  security:
    enabled: false
  health:
    redis:
      enabled: false
    rabbit:
      enabled: false

security:
  basic:
    enabled: false
  user:
    name: user
    password: password

server:
  port: 8080
  context-path: /supporttool
  undertow:
    buffer-size: 16384
    io-threads: 64
    worker-threads: 512
    direct-buffers: true

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: true
  cloud:
    bus:
      enabled: false

#Port defined in TDS_Build:docker-compose.yml
  rabbitmq:
    port: 32846

data:
  s3:
    access-key: ${s3.key}
    secret-key: ${s3.secret}
    bucket-name: tds-resources
    test-package-prefix: support-content/dev/test-packages

# URLs for dependent services
support-tool:
  art-rest-url: http://localhost:8080/rest
  assessment-url: http://localhost:32841
  thss-api-url: http://localhost:28039/api
  tis-api-url: http://localohst:53708/api

#SAML
saml:
  key-store-file: file:/Users/emunoz/saml/ernie-local.jks
  key-store-password: password123
  private-key-entry-alias: ernie-local
  private-key-entry-password: password
  idp-metadata-url: https://sso-deployment.sbtds.org/auth/oauth2/access_token?realm=/sbac
  sp-entity-id: ernie-local