# this app is expected to run inside the security perimeter so disable security for actuator end-points and,
# since those are the only end-points, switch to a less standard port using the main server.port config
management:
  port: 8008
  security:
    enabled: false
  health:
    redis:
      enabled: false
    rabbit:
      enabled: false

security:
  basic:
    enabled: false
  user:
    name: user
    password: password

server:
  port: 32850
  undertow:
    buffer-size: 16384
    io-threads: 64
    worker-threads: 512
    direct-buffers: true

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: true
  cloud:
    bus:
      enabled: false
  data:
    mongodb:
      uri: ${sbac.support.mongo.connection.uri}/support-tool

#Port defined in TDS_Build:docker-compose.yml
  rabbitmq:
    port: 32846

data:
  s3:
    access-key: ${s3.key}
    secret-key: ${s3.secret}
    bucket-name: tds-resources
    test-package-prefix: support-content/test-packages