# NOTE: The config files for service and external-apis should remain identical for easier maintenance, even
#       though some settings are specific to one or the other.
#
# this app is expected to run inside the security perimeter so disable security for actuator end-points and,
# since those are the only end-points, switch to a less standard port using the main server.port config
management:
  port: 8008
  security:
    enabled: false
  health:
    redis:
      enabled: false
    rabbit:
      enabled: false

server:
  port: 8080

internalClientPort: 8883

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: true
  cloud:
    bus:
      enabled: false
  http.multipart.max-file-size: 50MB

#Port defined in TDS_Build:docker-compose.yml
  rabbitmq:
    port: 32846

data:
  s3:
    access-key: ${s3.key}
    secret-key: ${s3.secret}
    bucket-name: tds-resources
    test-package-prefix: support-content/dev/test-packages

# OAuth2
security:
  oauth2:
    token-info-url: ${support-tool.token-info-url}

#SAML
saml:
  key-store-file: ${tds.java.keystore.file}
  key-store-password: ${tds.java.keystore.password}
  private-key-entry-alias: ${tds.java.private.key.alias}
  private-key-entry-password: ${tds.java.private.key.password}
  idp-metadata-url: ${tds.idp.metadata.url}
  sp-entity-id: ${tds.sp.entityid}

# URLs for dependent services
support-tool:
  art-rest-url: http://localhost:8080/rest
  assessment-url: http://localhost:32841
  exam-url: http://localhost:8081
  content-url:  http://localhost:32848
  thss-api-url: http://localhost:28039/api
  tis-api-url: http://localhost:53708/api
  permissions-url: ${support-tool.permissions-url}

  progman-tenant-level: STATE
  progman-tenant: CA
  progman-url: http://progman-web-deployment.sbtds.org:8080/rest/

  sso-client-id: ${support-tool.sso-client-id}
  sso-client-secret: ${support-tool.sso-client-secret}
  sso-password: ${support-tool.sso-password}
  sso-url: https://sso-deployment.sbtds.org/auth/oauth2/access_token?realm=/sbac
  token-info-url: https://sso-deployment.sbtds.org:443/auth/oauth2/tokeninfo?access_token={access_token}
  sso-username: ${support-tool.sso-username}

---
spring:
  profiles:
    active:
